version: '3'
services:
  php:
    image: php:8-fpm
    volumes:
      - ./:/var/www/html
  nginx:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html/
