name: release

on:
  push:
    branches:
      - 'main'
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ap-northeast-1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: set IMAGE_URL
        id: image-url
        run: echo "IMAGE_URL=${{ steps.login-ecr.outputs.registry }}/example_next_repo:${{ github.sha }}" >> $GITHUB_ENV
      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker build -t ${{ env.IMAGE_URL }} --build-arg build_id=${{ github.sha }} .
          docker push ${{ env.IMAGE_URL }}
      - name: deploy to lambda
        run: aws lambda update-function-code --function-name exampleNextRepo --image-uri ${{ env.IMAGE_URL }}

      - name: deploy static to s3
        run: aws s3 cp --recursive --region ap-northeast-1 ./.next/static s3://${{ secrets.S3_BUCKET }}/_next/static